//! Markdown round-tripping for `planning/open-items.md` (SPECIFICATION.md §5).
//!
//! The app is the sole producer of this format and the parser is correspondingly
//! strict: a broken file is a *loud* error, never silently half-applied state.
//! [`serialize`] and [`parse`] are inverse operations (covered by tests).

use std::fmt::Write as _;

use crate::domain::{Authority, ItemKind, ItemStatus, OpenItem, Priority};

const HEADER: &str =
    "# Open Items\n\n_Generated by Packet. Drive changes through chat or board actions._\n";

/// Serialize the full queue. Callers are responsible for ordering first
/// (see [`sort_queue`]); the writer faithfully preserves the given order.
pub fn serialize(items: &[OpenItem]) -> String {
    let mut out = String::with_capacity(items.len() * 220 + 256);
    out.push_str(HEADER);
    if items.is_empty() {
        out.push_str("\n_No open items. Everything captured is answered for now._\n");
        return out;
    }
    for item in items {
        out.push_str(&render_one(item));
    }
    out
}

fn render_one(i: &OpenItem) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "## {}\n", i.id);
    let _ = writeln!(s, "**Priority:** {}", i.priority);
    let _ = writeln!(s, "**Authority:** {}", i.authority);
    if let Some(key) = &i.conversation_id {
        let _ = writeln!(s, "**Conversation:** {key}");
    }
    let _ = writeln!(s, "**Type:** {}", i.kind);
    let _ = writeln!(s, "**Category:** {}", i.category);
    if let Some(id) = &i.feature_id {
        let _ = writeln!(s, "**Feature:** {id}");
    }
    let _ = writeln!(
        s,
        "**Assigned To:** {}",
        i.assigned_to.as_deref().unwrap_or("(unassigned)")
    );
    let _ = writeln!(s, "**Status:** {:#?}", i.status);
    let _ = writeln!(s, "\n### Question\n{}\n", i.question.trim());
    let _ = writeln!(s, "\n### Reason\n{}\n", i.reason.trim());
    if !i.recommendation.is_empty() {
        let _ = writeln!(s, "\n### Recommendation\n{}\n", i.recommendation.trim());
    }
    if !i.evidence.is_empty() {
        let _ = writeln!(s, "\n### Evidence\n{}\n", i.evidence.trim());
    }
    s
}

/// Queue ordering per §9: Blocking → High → Normal, ties broken by ID so the
/// panel and file stay deterministic between agent rerankings.
pub fn sort_queue(items: &mut [OpenItem]) {
    items.sort_by(|a, b| a.priority.cmp(&b.priority).then_with(|| a.id.cmp(&b.id)));
}

/// Parse the artifact back into the structured queue (only Open items ever
/// reach the file; the parser stamps `Open`).
pub fn parse(text: &str) -> Result<Vec<OpenItem>, String> {
    let mut items: Vec<OpenItem> = Vec::new();
    let mut cur: Option<Partial> = None;

    for line in text.lines() {
        let t = line.trim();

        if let Some(rest) = t.strip_prefix("## ") {
            if let Some(prev) = cur.take() {
                prev.finish(&mut items)?;
            }
            let id = rest.trim().to_string();
            if !crate::core::ids::is_valid_id(&id) {
                return Err(format!(
                    "malformed item heading '## {rest}' (expected e.g. CLR-012)"
                ));
            }
            cur = Some(Partial::new(id));
            continue;
        }

        let Some(p) = cur.as_mut() else { continue }; // preamble / header text
        if t.is_empty() {
            continue;
        }
        // Section headers keep working for the life of the item, so a
        // `### Reason` landing after a blank line still switches buffers.
        if let Some(sub) = t.strip_prefix("### ") {
            p.enter_section(sub.trim());
        } else if p.mode() == Capture::Field {
            // Bold field lines are only recognized in the item header
            // region; once a body starts, prose keeps its asterisks.
            if let Some((key, value)) = bold_field(t) {
                p.field(key, value)?;
            }
        } else if let Some(buf) = p.capture_buffer() {
            push_line(buf, line);
        }
    }
    if let Some(prev) = cur.take() {
        prev.finish(&mut items)?;
    }
    Ok(items)
}

/// Push one body line onto an accumulator, separating paragraphs.
fn push_line(buf: &mut String, line: &str) {
    if !buf.is_empty() {
        buf.push('\n');
    }
    buf.push_str(line.trim_end());
}

/// Split `**Key:** value` → `(Key, value)`, when the line is a field line.
fn bold_field(line: &str) -> Option<(&str, &str)> {
    let inner = line.strip_prefix("**")?;
    let idx = inner.find("**")?;
    let key = inner[..idx].trim().trim_end_matches(':');
    let value = inner[idx + 2..].trim();
    Some((key, value))
}

/// Accumulator for one item while scanning lines.
struct Partial {
    id: String,
    conversation_id: Option<String>,
    priority: Option<Priority>,
    authority: Option<Authority>,
    kind: Option<ItemKind>,
    category: Option<String>,
    assigned_to: Option<String>,
    _status: Option<ItemStatus>,
    mode: Capture,
    question_buf: String,
    reason_buf: String,
    feature_id: Option<String>,
    recommendation_buf: String,
    evidence_buf: String,
}

#[derive(Clone, Copy, PartialEq)]
enum Capture {
    Field,
    Question,
    Reason,
    Recommendation,
    Evidence,
    Ignore,
}

macro_rules! parse_val {
    ($t:ident, $key:expr, $v:expr) => {
        match $t::parse_i($v) {
            Some(v) => v,
            None => return Err(format!("bad '{}' value: '{}'", $key, $v)),
        }
    };
}

impl Partial {
    fn new(id: String) -> Self {
        Self {
            id,
            conversation_id: None,
            priority: None,
            authority: None,
            kind: None,
            category: None,
            assigned_to: None,
            _status: None,
            mode: Capture::Field,
            question_buf: String::new(),
            reason_buf: String::new(),
            feature_id: None,
            recommendation_buf: String::new(),
            evidence_buf: String::new(),
        }
    }

    fn enter_section(&mut self, name: &str) {
        self.mode = match name {
            "Question" => Capture::Question,
            "Reason" => Capture::Reason,
            "Recommendation" => Capture::Recommendation,
            "Evidence" => Capture::Evidence,
            _ => Capture::Ignore,
        };
    }

    fn capture_buffer(&mut self) -> Option<&mut String> {
        match self.mode {
            Capture::Question => Some(&mut self.question_buf),
            Capture::Reason => Some(&mut self.reason_buf),
            Capture::Recommendation => Some(&mut self.recommendation_buf),
            Capture::Evidence => Some(&mut self.evidence_buf),
            _ => None,
        }
    }

    const fn mode(&self) -> Capture {
        self.mode
    }

    fn field(&mut self, key: &str, value: &str) -> Result<(), String> {
        match key {
            "Priority" => self.priority = Some(parse_val!(Priority, key, value)),
            "Authority" => self.authority = Some(parse_val!(Authority, key, value)),
            "Type" => self.kind = Some(parse_val!(ItemKind, key, value)),
            "Status" => self._status = Some(parse_val!(ItemStatus, key, value)),
            "Category" => self.category = Some(value.to_string()),
            "Feature" => self.feature_id = Some(value.to_string()),
            "Conversation" => self.conversation_id = Some(value.to_string()),
            "Assigned To" => {
                self.assigned_to = if value == "(unassigned)" {
                    None
                } else {
                    Some(value.to_string())
                }
            }
            other => return Err(format!("unknown item field '{other}'")),
        }
        Ok(())
    }

    fn finish(self, items: &mut Vec<OpenItem>) -> Result<(), String> {
        let question = self.question_buf.trim().to_string();
        if question.is_empty() {
            return Err(format!("{}: missing '### Question' section", self.id));
        }
        if self.priority.is_none() {
            return Err(format!("{}: missing '**Priority:**'", self.id));
        }
        if self.kind.is_none() {
            return Err(format!("{}: missing '**Type:**'", self.id));
        }
        let Some(category) = self.category.filter(|c| !c.trim().is_empty()) else {
            return Err(format!("{}: missing '**Category:**'", self.id));
        };
        let mut item = OpenItem::new(
            self.id,
            self.priority.unwrap(),
            self.kind.unwrap(),
            category,
            self.assigned_to,
            question,
            self.reason_buf.trim().to_string(),
        );
        if items.iter().any(|existing| existing.id == item.id) {
            return Err(format!("duplicate open item id {}", item.id));
        }
        item.authority = self.authority.unwrap_or(Authority::Human);
        item.conversation_id = self.conversation_id;
        item.feature_id = self.feature_id;
        item.recommendation = self.recommendation_buf.trim().to_string();
        item.evidence = self.evidence_buf.trim().to_string();
        items.push(item);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_items() -> Vec<OpenItem> {
        let mut v = vec![
            OpenItem::new(
                "CLR-001".into(),
                Priority::Blocking,
                ItemKind::Ambiguity,
                "Security".into(),
                Some("InfoSec".into()),
                "Should API tokens expire automatically?\nOr live until revoked?".into(),
                "Token creation defined, lifetime is not.".into(),
            ),
            OpenItem::new(
                "CLR-002".into(),
                Priority::Normal,
                ItemKind::Question,
                "Product".into(),
                None,
                "What happens when an export is interrupted?".into(),
                "Unspecified in the conversation.".into(),
            ),
        ];
        v[0].authority = Authority::Review;
        v[0].feature_id = Some("CHG-001".into());
        v[0].recommendation =
            "Use expiring tokens; a reviewer can approve this provisional direction.".into();
        v[0].evidence = "api/src/tokens.rs documents the current persistent token behavior.".into();
        sort_queue(&mut v);
        v
    }

    #[test]
    fn serialize_parse_round_trip_preserves_everything() {
        for _ in 0..2 {
            let items = sample_items();
            let md = serialize(&items);
            let back = parse(&md).expect("parse own output");
            assert_eq!(back, items);
        }
    }

    #[test]
    fn empty_queue_marker_survives() {
        let md = serialize(&[]);
        assert!(parse(&md).unwrap().is_empty());
        let with = serialize(&sample_items());
        assert!(!with.contains("_No open items"));
    }

    #[test]
    fn rejects_duplicate_ids_and_missing_question() {
        let bad = "## CLR-001\n\n**Priority:** High\n**Type:** Question\n**Category:** QA\n**Assigned To:** Taylor\n\n### Question\nA?\n\n### Reason\nr\n\n## CLR-001\n\n**Priority:** High\n**Type:** Question\n**Category:** QA\n\n### Question\nB?\n\n### Reason\nr\n";
        assert!(parse(bad).is_err());
        let missing = "## CLR-007\n\n**Priority:** High\n**Type:** Question\n**Category:** QA\n\n### Reason\nforgot question\n";
        assert!(parse(missing).is_err());
    }

    #[test]
    fn field_lookalike_inside_question_does_not_break_parse() {
        let md = "## CLR-009\n\n**Priority:** High\n**Type:** Question\n**Category:** QA\n**Assigned To:** (unassigned)\n\n### Question\n**Note:** bold prose here must stay in the question.\nSecond line.\n\n### Reason\nr\n";
        let v = parse(md).unwrap();
        assert!(v[0].question.starts_with("**Note:**"));
        assert!(v[0].question.contains("Second line."));
    }

    #[test]
    fn unassigned_placeholder_parses_to_none() {
        let md = "## CLR-003\n\n**Priority:** High\n**Type:** Assumption\n**Category:** Ops\n**Assigned To:** (unassigned)\n\n### Question\nAssumed? \n\n### Reason\nWhy\n";
        let v = parse(md).unwrap();
        assert_eq!(v[0].assigned_to, None);
        assert_eq!(v[0].reason, "Why");
    }
}
