//! Markdown round-tripping for `.kool-ade-packet/planning/open-items.md` (SPECIFICATION.md §5).
//!
//! The app is the sole producer of this format and the parser is correspondingly
//! strict: a broken file is a *loud* error, never silently half-applied state.
//! [`serialize`] and [`parse`] are inverse operations (covered by tests).

use std::fmt::Write as _;

use crate::domain::OpenItem;

mod parser;
pub use parser::parse;

const HEADER: &str =
    "# Open Items\n\n_Generated by Packet. Drive changes through chat or board actions._\n";

/// Serialize the full queue. Callers are responsible for ordering first
/// (see [`sort_queue`]); the writer faithfully preserves the given order.
pub fn serialize(items: &[OpenItem]) -> String {
    let mut out = String::with_capacity(items.len() * 220 + 256);
    out.push_str(HEADER);
    if items.is_empty() {
        out.push_str("\n_No open items. Everything captured is answered for now._\n");
        return out;
    }
    for item in items {
        out.push_str(&render_one(item));
    }
    out
}

fn render_one(i: &OpenItem) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "## {}\n", i.id);
    if let Some(uid) = &i.uid {
        let _ = writeln!(s, "**UID:** {uid}");
    }
    let _ = writeln!(s, "**Priority:** {}", i.priority);
    let _ = writeln!(s, "**Authority:** {}", i.authority);
    if let Some(key) = &i.conversation_id {
        let _ = writeln!(s, "**Conversation:** {key}");
    }
    let _ = writeln!(s, "**Type:** {}", i.kind);
    let _ = writeln!(s, "**Category:** {}", i.category);
    if let Some(id) = &i.feature_id {
        let _ = writeln!(s, "**Feature:** {id}");
    }
    if let Some(uid) = &i.feature_uid {
        let _ = writeln!(s, "**Feature UID:** {uid}");
    }
    if !i.blocked_by.is_empty() {
        let _ = writeln!(s, "**Blocked By:** {}", i.blocked_by.join(", "));
    }
    if let Some(brief) = &i.decision_brief {
        let encoded = serde_json::to_string(brief).expect("decision brief JSON serialization");
        let _ = writeln!(s, "**Decision Brief:** {encoded}");
    }
    let _ = writeln!(
        s,
        "**Assigned To:** {}",
        i.assigned_to.as_deref().unwrap_or("(unassigned)")
    );
    let _ = writeln!(s, "**Status:** {:#?}", i.status);
    let _ = writeln!(s, "\n### Question\n{}\n", i.question.trim());
    let _ = writeln!(s, "\n### Reason\n{}\n", i.reason.trim());
    if !i.recommendation.is_empty() {
        let _ = writeln!(s, "\n### Recommendation\n{}\n", i.recommendation.trim());
    }
    if !i.evidence.is_empty() {
        let _ = writeln!(s, "\n### Evidence\n{}\n", i.evidence.trim());
    }
    s
}

/// Queue ordering per §9: Blocking → High → Normal, ties broken by ID so the
/// panel and file stay deterministic between agent rerankings.
pub fn sort_queue(items: &mut [OpenItem]) {
    items.sort_by(|a, b| a.priority.cmp(&b.priority).then_with(|| a.id.cmp(&b.id)));
}

#[cfg(test)]
mod tests;
